const LOPB_STRING_JV = '<article > <section id="title">Letter of Price Bid</section> <section id="topRightText"> <p>Date: <span>DATE</span></p> <p>Name of the Contract: <span>FULL_CONTRACT_NAME</span></p> <p>Invitation for Bid No.: <span>INVITATION_BID_NO</span></p> <p>Contract Identification No.: <span >CONTRACT_ID_NO</span></p> </section> <section id="toPart"> <p >To:</p> <span > TO_TEXT </span> </section> <section  id="mainContent"> <p >We, the undersigned, declare that:</p> <ol type="a"> <li>We have examined and have no reservations to the Bidding Documents, including Addenda issued in accordance with Instructions to Bidders (ITB) Clause8.</li> <li>We offer to execute in conformity with the Bidding Documents the following Works:<br><span>CONTRACT_ID_NO</span></li> <li>The total price of our Bid, excluding any discounts offered in item (d) below is: <span>NRs............</span>;<br>or when left blank is the Bid Price indicated in the Bill of Quantities.</li> <li>The discounts offered and the methodology for their application are:<span>............</span></li> <li>Our bid shall be valid for a period of <span>BID_VAL_PERIOD</span> from the date fixed for the bid submission deadline in accordance with the Bidding Documents, and it shall remain binding upon us and may be accepted at any time before the expiration of that period;</li> <li>If our bid is accepted, we commit to obtain a performance security in accordance with the Bidding Document;</li> <li>We have paid, or will pay the following commissions, gratuities, or fees with respect to the bidding process or execution of the Contract: <table > <thead> <td>Name of Recipient</td> <td>Address</td> <td>Reason</td> <td>Amount</td> </thead> <tr> <td><span>None</span></td> <td><span>None</span></td> <td><span>None</span></td> <td><span>None</span></td> </tr> </table> </li> <li>We understand that this bid, together with your written acceptance thereof included in your notification of award, shall constitute a binding contract between us, until a formal contract is prepared and executed;</li> <li>We understand that you are not bound to accept the lowest evaluated bid or any other bid that you may receive; and</li> <li>We declare that we are solely responsible for the authenticity of the documents submitted by us.</li> <li>We agree to permit the Employer/DP or its representative to inspect our accounts and records and other documents relating to the bid submission and to have them audited by auditors appointed by the Employer.</li> </ol> </section> <section id="bottomLeftText"> <p >Name: <span >AP</span></p> <p >In the Capacity of <span >Authorized JV Partner</span></p> <br><br> <p >Signed: <span >............</span></p> <p >Duly authorized to sign for and on behalf of <span >JV_NAME</span></p> <p >Date: <span >DATE</span></p> </section> </article>'

getLopb = (formJSON)=> LOPB_STRING_JV
		.replaceAll('DATE',formJSON.date)
		.replaceAll('FULL_CONTRACT_NAME',formJSON.contractName)
		.replaceAll('INVITATION_BID_NO',formJSON.bidNo)
		.replaceAll('CONTRACT_ID_NO',formJSON.contractId)
		.replaceAll('TO_TEXT',formJSON.to)
		.replaceAll('BID_VAL_PERIOD',formJSON.bidVal)
		.replaceAll('AP',formJSON.authorized)
		.replaceAll('JV_NAME',formJSON.firmName)
		.replaceAll('*','<br>')
